### PR TITLE
Adds current_url as a whitelisted method to passthrough to selenium driver

### PR DESCRIPTION
**Pull request by aliking**
* Update specs to use a static file instead of needing internet access.
* Mock out AgentConnector so that it doesn't really get a session, need a key or submit match requests. This stops the tests covering end-to-end functionality, but that's not explicitly what they are testing anyway.
* Combine existing tests into a test of methods that pass through to the Selenium driver. I've not added more methods to this, though.

### CODE REVIEW

**Comment by danielputerman** [comment]
Great PR, thanks! We've just added a feature for automatic handling of image rotation in Appium, which is why it took a while to respond.

**Comment by danielputerman** [comment]
Unfortunately I can't mark the PR as merged manually, but I'd be happy to add you as a contributor to the repository (e.g., get the latest commits and create another pull request changing 'dummy_key' to 'DUMMY_KEY' in the driver_pass_through file, and I'll merge it).

**Comment by aliking** [comment]
No worries, I'm just happy to have the change in; I prefer not to maintain
a fork if I can help it. Thanks, Ali

On Thu, Apr 23, 2015 at 8:09 PM, danielputerman <notifications@github.com>
wrote:

> Closed #3 <https://github.com/applitools/Eyes.Selenium.Ruby/pull/3>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/applitools/Eyes.Selenium.Ruby/pull/3#event-288838750>.
>



-- 
alastair king
tech lead - test
animoto productions
ali@animoto.com
347.635.4647

**Comment by danielputerman** [comment]
I'll make sure it's merged correctly anyways, you won't have to maintain the fork. Thanks again :)

**Pull request merged**
